### ISSUE TITLE
tidy_bytes': undefined method `empty?' 

### ISSUE THREAD

**Issue by willwade** [jipiboily/tumblr-to-hugo#1]
Not sure what this is - Im guessing an empty string somewhere? 

on running:

> ruby t2h.rb API+KEY willwade.tumblr.com

I get...

`We're done!
Writing 2012-12-05-how-to-get-a-exchange-2003-public-shared-calendar-on-an-iphone-using-outlook-2007-and-maybe-dropbox.html
Writing 2012-05-15-keyboard-sounder.html
Writing 2012-03-20-extract-images-sounds-from-clicker-files.html
/Users/willwade/.rvm/gems/ruby-2.3.2/gems/activesupport-5.0.0.1/lib/active_support/multibyte/unicode.rb:246:in `tidy_bytes': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /Users/willwade/.rvm/gems/ruby-2.3.2/gems/activesupport-5.0.0.1/lib/active_support/inflector/transliterate.rb:62:in `transliterate'
	from /Users/willwade/.rvm/gems/ruby-2.3.2/gems/activesupport-5.0.0.1/lib/active_support/inflector/transliterate.rb:88:in `parameterize'
	from /Users/willwade/Downloads/tumblr-to-hugo-master/hugo.rb:14:in `write_post'
	from t2h.rb:23:in `block (2 levels) in <main>'
	from t2h.rb:22:in `each'
	from t2h.rb:22:in `block in <main>'
	from /Users/willwade/.rvm/rubies/ruby-2.3.2/lib/ruby/2.3.0/csv.rb:1282:in `open'
	from t2h.rb:20:in `<main>'
`

**Comment by jipiboily** [comment]
The problem seems to be on that line: https://github.com/jipiboily/tumblr-to-hugo/blob/master/hugo.rb#L14

Do you have a post with no title? Would it be possible? Hard to test without your API key I guess. 😕

**Comment by willwade** [comment]
Yep. Pretty sure it's a post without title.

**Comment by willwade** [comment]
Ps thanks for looking!

**Comment by jipiboily** [comment]
What should happen in this case? Skip it? Without the title the filename will be empty, so does the URL.

You could change the code to skip empty titles maybe?

JP Boily
Founder @ Metrics Watch http://metricswatch.com
